/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testthi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class thi extends javax.swing.JFrame {
        int current;    
        ArrayList<sachh> list=new ArrayList<>();
         public void loadDataToArray(){
          try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");      //1:Nạp driver
            String url="jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;";   //2Định nghĩa  Connection URL
            Connection con = DriverManager.getConnection(url,"sa","00112233");                                //Kết nối CSDL bằng đối tượng Connection
            String sql="select * from sach"; //Thi hành câu truy vấn trên table NV trong SQL Sever
             Statement stm = con.createStatement(); //Tạo đối tượng Statement
            ResultSet rs = stm.executeQuery(sql);
            list.clear();
            while(rs.next()){                                //Xử lý kết quả
                sachh sv= new sachh();
               sv.setMasach(rs.getString("masach"));
                sv.setTensach(rs.getString("tensach"));
                sv.setTacgia(rs.getString("tacgia"));
                sv.setTheloai(rs.getString("theloai"));
                sv.setNhaXB(rs.getString(5));
                
                
                list.add(sv);
                System.out.println("Connected");
                
            }
            con.close();             //Đóng kết nối
        }catch(Exception e){
             System.out.println("connect failure!");
            System.out.println(e);
           
            
        }
          
    }
      public void display(int i){
        sachh sv = list.get(i);
        txtmasach.setText(sv.getMasach());
        txttensach.setText(sv.getTensach());
        txttacgia.setText(""+sv.getTacgia());
        txttheloai.setText(""+sv.getTheloai());
        txtnnhaxb.setText(""+sv.getNhaXB());          
    }    
      
      public void clear(){
          txtmasach.setText("");
          txttensach.setText("");
          txttacgia.setText("");
          txttheloai.setText("");
          txtnnhaxb.setText("");      
      }
         
         

    /**
     * Creates new form thi
     */
    public thi() {
        initComponents();
        loadDataToArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmasach = new javax.swing.JTextField();
        txttensach = new javax.swing.JTextField();
        txttacgia = new javax.swing.JTextField();
        txttheloai = new javax.swing.JTextField();
        txtnnhaxb = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quản Lý Sách");

        jLabel2.setText("Mã sách");

        jLabel3.setText("Tên sách");

        jLabel4.setText("Tác giả");

        jLabel5.setText("Thể loại");

        jLabel6.setText("Nhà xuất bản");

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsearch.setText("Sreach");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btn1.setText("|<");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("<<");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText(">>");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn44.setText(">|");
        btn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2)
                        .addGap(18, 18, 18)
                        .addComponent(btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn44)
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnnhaxb, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmasach)
                                    .addComponent(txttensach)
                                    .addComponent(txttacgia)
                                    .addComponent(txttheloai, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnadd)
                                        .addComponent(btndelete))
                                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(btnsave))
                            .addComponent(btnsearch, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnnhaxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn44))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        current = 0;
        display(current);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        clear();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");      //1:Nạp driver
            String url="jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;";   //2Định nghĩa  Connection URL
            Connection con = DriverManager.getConnection(url,"sa","00112233");                                //Kết nối CSDL bằng đối tượng Connection
            Statement stm = con.createStatement();          //Tạo đối tượng Statement    
          String sql= "insert into sach (masach,tensach,tacgia,theloai,nhaxb) values(?,?,?,?,?)";
             // String sql = "delete from Student where MaSV =?";
             //String sql = "update student set HOTEN=?,SODT=?,GIOITINH=?,DIACHI=?,EMAIL=? WHERE MASV=?";
      
           PreparedStatement st=con.prepareStatement(sql);
           st.setString(1,txtmasach.getText());
           st.setString(2,txttensach.getText());
           st.setString(3,txttacgia.getText());
           st.setString(4,txttheloai.getText());
           st.setString(5, txtnnhaxb.getText());
           st.executeUpdate();
           JOptionPane.showMessageDialog(this,"Save thành công");
            con.close();             //Đóng kết nối
              //display(current()--);
              loadDataToArray();
              clear();
              
             // loadDataTotable();
             /// cleanfrom();
              
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"SINH VIÊN ĐÃ TỒN TẠI");
            
        }  
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
          if (current == 0) {
            JOptionPane.showMessageDialog(null, "Đang Ở Đầu Danh Sách");
            return;
        }
        current--;
        display(current);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         if (current == list.size() - 1){
            JOptionPane.showMessageDialog(null, "Đang Ở Cuối Chuỗi");
            return;
        }
        current ++;
        display(current);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn44ActionPerformed
          current = list.size() - 1;
        display(current);
    }//GEN-LAST:event_btn44ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");      //1:Nạp driver
            String url="jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;";   //2Định nghĩa  Connection URL
            Connection con = DriverManager.getConnection(url,"sa","00112233");                                //Kết nối CSDL bằng đối tượng Connection
            Statement stm = con.createStatement();          //Tạo đối tượng Statement    
          //String sql= "insert into GRADE(MASV,TIENGANH,TINHOC,GDTC) values(?,?,?,?)";
             String sql = "delete from sach where masach =?";
             //String sql = "update student set HOTEN=?,SODT=?,GIOITINH=?,DIACHI=?,EMAIL=? WHERE MASV=?";
      
           PreparedStatement st=con.prepareStatement(sql);
           st.setString(1,txtmasach.getText());
           st.executeUpdate();
           JOptionPane.showMessageDialog(this,"delete thành công");
            con.close();             //Đóng kết nối
              //display(current()--);
              loadDataToArray();        
              clear();
            //  loadDataTotable();
              //cleanfrom();
        }catch(Exception e){
            System.out.println(e);
            
        }  
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");      //1:Nạp driver
            String url="jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;";   //2Định nghĩa  Connection URL
            Connection con = DriverManager.getConnection(url,"sa","00112233");                                //Kết nối CSDL bằng đối tượng Connection
            String sqlString = "update sach set tensach = ?, tacgia = ?,theloai = ?,nhaxb = ? where masach = ?";
            PreparedStatement ps=con.prepareStatement(sqlString);
            ps.setString(1, txttensach.getText());
            ps.setString(2, txttacgia.getText());
            ps.setString(3, txttheloai.getText());
            ps.setString(4,txtnnhaxb.getText());           
            ps.setString(5, txtmasach.getText());
            int result = ps.executeUpdate();
            if(result == 1){
                JOptionPane.showMessageDialog(this, "cap nhat thanh cong");
               clear();
            }
            else{
                JOptionPane.showMessageDialog(this, "cap nhat khong thanh cong");
                
            }
            con.close();
            loadDataToArray();
           // loadDataTotable();  
        }catch(Exception e){
            System.out.println(e);
            
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
       try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");      //1:Nạp driver
            String url="jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true;";   //2Định nghĩa  Connection URL
            Connection con = DriverManager.getConnection(url,"sa","00112233");   
              PreparedStatement stm=con.prepareStatement("select * from sach where masach=?");
              stm.setString(1,txtmasach.getText());
              ResultSet rs= stm.executeQuery();
              if(rs.next()){
                  
                txttensach.setText(rs.getString(2));
                txttacgia.setText(rs.getString(3));
                txttheloai.setText(rs.getString(4));
                txtnnhaxb.setText(rs.getString(5));               
                txtmasach.setText(rs.getString(1));
               
              
              }
              else{
                  JOptionPane.showMessageDialog(this,"SINH VIÊN KHÔNG TỒN TẠI");
              }
         } catch (Exception e) {
             System.out.println(e);
         } 
        
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtmasach;
    private javax.swing.JTextField txtnnhaxb;
    private javax.swing.JTextField txttacgia;
    private javax.swing.JTextField txttensach;
    private javax.swing.JTextField txttheloai;
    // End of variables declaration//GEN-END:variables
}
